data <- read.csv("health_claims.csv")
data$month <- as.Date(paste0(data$month, "-01"))
ts_data <- ts(data$claim_cost, start = c(2021, 1), frequency = 12)
plot(ts_data, main = "Monthly Claim Cost Trend", ylab = "Cost", xlab = "Year")
decomp <- decompose(ts_data)
plot(decomp)
model_hw <- HoltWinters(ts_data)
forecasted <- forecast::forecast(model_hw, h = 6)
plot(forecasted)
library(forecast)
model_arima <- auto.arima(ts_data)
forecast_arima <- forecast(model_arima, h = 6)
plot(forecast_arima)
accuracy(forecasted)
png("claim_cost_forecast.png")
plot(forecasted, main="Forecast of Claim Costs")
dev.off()
